Algoritmo "Constantes"
// Disciplina   : [Linguagem e Lógica de Programação]
// Descrição   : Neste exemplo, mostramos como funciona uma constante
//               Aqui, não há declaração de variável pois PI já é uma constante
//               do visualg
// Autor       : Akbar Miranda
// Data atual  : 29/10/2022
Var
// Seção de Declarações das variáveis 


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("O valor primitivo de PI é: ", PI)

Fimalgoritmo