Algoritmo "multiplos0a100"
// Disciplina   : [Linguagem e Lógica de Programação]
// Descrição   : Neste algorítmo, imprimimos os múltiplos de 2 de 0 até 100
// Autor(a)    : Akbar Miranda
// Data atual  : 01/11/2022
Var
// Seção de Declarações das variáveis 
 n:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
  escreval ("Abaixo estão os múltiplos de 2 entre 0 e 100")
  para n de 2 ate 100 passo n+2 faca
  escreval(n)
  fimpara

Fimalgoritmo