Algoritmo "Seu Nome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Descrição   : Neste programa, você digita seu nome e recebe uma mensagem de boas vindas
// Autor    : Akbar Miranda
// Data atual  : 29/10/2022
Var
// Seção de Declarações das variáveis
  nome: caractere


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...

escreva("Digite o seu nome: ")
    leia(nome)

    escreva("Seja muito bem vindo: ", nome)



Fimalgoritmo