Algoritmo "tabuadaenquanto"
// Disciplina   : [Linguagem e Lógica de Programação]
// Descrição   : Tabuada com enquanto
// Autor(a)    : Akbar Miranda
// Data atual  : 02/11/2022
Var
// Seção de Declarações das variáveis 
 j:real
 q:inteiro
 

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite um  número qualquer que deseja imprimir a tabuada até 10")
leia(j)
q<-1
enquanto q<11  faca
escreval(j," x ",q, " = ",j*q)
q<-q+1
fimenquanto

Fimalgoritmo